### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by craigcallen** [fahmifitu/colorful-yt#1]
Getting an error when installing on the latest version of Wordpress. Any ideas?

**Comment by fahmifitu** [comment]
@craigcallen Can you please share the error? I tested on latest WP version with no issues.

**Comment by craigcallen** [comment]
I did a manual install and everything was fine, when I did an install with a zip file via Wordpress - received an invalid archive error. But, manual installation works, great plugin.

**Comment by craigcallen** [comment]
The error I was referencing is explained here: https://diviextended.com/incompatible-archive-error-in-wordpress/ - Appears to be a MacOS issue not the plugin.
